### ISSUE TITLE
Clean up UI

### ISSUE THREAD

**Issue by ekam-g** [MrSyn88/fellowship-portfolio#19]
let's agree and try to make it look even better with maybe animations

**Comment by MrSyn88** [comment]
Sounds good

**Comment by ekam-g** [comment]
okay for this, like make it look like mlh style like https://fellowship.mlh.io/. MLH does have diffrent styles but let's keep like how they make their fellowship stuff, including like this website https://lms.fellowship.mlh.io

this is the final task and will be yours to do.
